import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, expect, it, vi } from 'vitest';
import { createPendingGroups, readPendingGroups, retirePendingGroup } from '../src/project/pending-groups';
const roots: string[] = [];
afterEach(async () => { await Promise.all(roots.splice(0).map(root => rm(root, { recursive: true, force: true }))); });
async function fixture() {
  const root = await mkdtemp(join(tmpdir(), 'pending-groups-')); roots.push(root);
  const file = join(root, 'pending-groups.json');
  const verify = vi.fn(async (_chatId: string): Promise<string | null> => 'Research');
  const eligible = vi.fn(async () => true);
  const onError = vi.fn();
  const options = { file, verify, eligible, onError };
  return { ...options, queue: createPendingGroups(options) };
}
it('persists the event before lookup, deduplicates concurrent deliveries and resumes after restart', async () => {
  const f = await fixture();
  await Promise.all(Array.from({ length: 8 }, () => f.queue.add('oc_a', 'ou_admin')));
  expect(f.verify).not.toHaveBeenCalled();
  const [candidate] = await readPendingGroups(f.file);
  expect(candidate).toMatchObject({ state: 'verifying', chatId: 'oc_a', operator: 'ou_admin' });
  f.verify.mockRejectedValueOnce(new Error('offline'));
  await f.queue.refresh();
  expect(await readPendingGroups(f.file)).toEqual([candidate]);
  await createPendingGroups(f).refresh();
  expect(await readPendingGroups(f.file)).toEqual([{ ...candidate, state: 'ready', name: 'Research' }]);
  await f.queue.add('oc_a', 'ou_admin');
  expect(await readPendingGroups(f.file)).toHaveLength(1);
});
it('does not revive removal or let an old lookup rename a re-added group', async () => {
  const f = await fixture();
  let release = (_name: string): void => {};
  f.verify.mockImplementationOnce(() => new Promise(resolve => { release = resolve; }));
  await f.queue.add('oc_a', 'ou_admin');
  const first = await readPendingGroups(f.file);
  const refreshing = f.queue.refresh();
  await vi.waitFor(() => expect(f.verify).toHaveBeenCalled());
  await f.queue.remove('oc_a');
  await f.queue.add('oc_a', 'ou_admin');
  release('Stale name');
  await refreshing;
  const current = await readPendingGroups(f.file);
  expect(current[0]?.generation).not.toBe(first[0]?.generation);
  expect(current[0]?.state).toBe('verifying');
  await f.queue.refresh();
  expect((await readPendingGroups(f.file))[0]).toMatchObject({ name: 'Research' });
  await retirePendingGroup(f.file, 'oc_a');
  expect(await readPendingGroups(f.file)).toEqual([]);
});
it('drops bound, no-longer-admin and departed groups, without enumerating historical memberships', async () => {
  const f = await fixture();
  await f.queue.refresh();
  expect(f.verify).not.toHaveBeenCalled();
  await f.queue.add('oc_a', 'ou_admin');
  f.eligible.mockResolvedValue(false);
  await f.queue.refresh();
  expect(f.verify).not.toHaveBeenCalled();
  expect(await readPendingGroups(f.file)).toEqual([]);
  f.eligible.mockResolvedValue(true);
  f.verify.mockResolvedValue(null);
  await f.queue.add('oc_a', 'ou_admin');
  await f.queue.refresh();
  expect(await readPendingGroups(f.file)).toEqual([]);
});
it('keeps bots isolated and reports corrupt files instead of silently dropping records', async () => {
  const a = await fixture(); const b = await fixture();
  await a.queue.add('oc_same', 'ou_a'); await b.queue.add('oc_same', 'ou_b');
  await a.queue.remove('oc_same');
  expect(await readPendingGroups(a.file)).toEqual([]);
  expect(await readPendingGroups(b.file)).toHaveLength(1);
  await writeFile(a.file, '{');
  await expect(readPendingGroups(a.file)).rejects.toThrow();
  await expect(a.queue.add('oc_new', 'ou_a')).rejects.toThrow();
  expect(await readFile(a.file, 'utf8')).toBe('{');
});
