import { randomUUID } from 'node:crypto';
import { readFile, mkdir, rename, rm, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { paths } from '../../config/paths';

const PROFILE = `# Generated by feishu-codex-bridge. Changes are replaced on startup.
# stdout is reserved for newline-delimited JSON-RPC.

- id: sdk-jsonrpc-server
  name: '@deepseek-ai/dsh-sdk-jsonrpc-server'
  config:
    maxTokensAsSuccess: true

- id: credentials
  name: '@deepseek-ai/dsh-credentials-local'

- id: llm
  name: '@deepseek-ai/dsh-llm-pi-ai'
  config:
    providers:
      moonshotai-cn:
        apiKeyEnv: MOONSHOT_API_KEY
        reasoning: !!js process.env.FEISHU_CODEX_BRIDGE_DSH_EFFORT ?? 'high'
        modelOverrides:
          kimi-k3:
            reasoningEfforts:
              off:
              low: low
              high: high
              max: max
          kimi-k2.7-code:
            reasoningEfforts:
              off:
              high: high
      zai-coding-cn:
        apiKeyEnv: ZAI_CODING_CN_API_KEY
        reasoning: !!js process.env.FEISHU_CODEX_BRIDGE_DSH_EFFORT ?? 'high'
        modelOverrides:
          glm-5.2:
            reasoningEfforts:
              off:
              low: low
              high: high
              max: max
          glm-5.1:
            reasoningEfforts:
              off:
              low: low
              high: high
              max: max
      minimax:
        apiKeyEnv: MINIMAX_API_KEY
        reasoning: !!js process.env.FEISHU_CODEX_BRIDGE_DSH_EFFORT ?? 'high'
        modelOverrides:
          MiniMax-M3:
            reasoningEfforts:
              off:
              high: high
          MiniMax-M2.7:
            reasoningEfforts:
              off:
              high: high
      deepseek:
        apiKeyEnv: DEEPSEEK_API_KEY
        reasoning: !!js process.env.FEISHU_CODEX_BRIDGE_DSH_EFFORT ?? 'high'
        modelOverrides:
          deepseek-v4-flash:
            reasoningEfforts:
              off:
              low: low
              high: high
              max: max
          deepseek-v4-pro:
            reasoningEfforts:
              off:
              low: low
              high: high
              max: max

- id: sandbox
  name: '@deepseek-ai/dsh-sandbox-local'

- id: sandbox-policy
  name: '@deepseek-ai/dsh-sandbox-policy'
  config:
    mode: danger-full-access
    workspaceRoot: !!js process.env.DSH_CWD ?? process.cwd()

- id: subprocess
  name: '@deepseek-ai/dsh-subprocess-local'

- id: bash
  name: '@deepseek-ai/dsh-bash-sandbox'
  config:
    cwd: !!js process.env.DSH_CWD ?? process.cwd()
    timeoutMs: 300000

- id: approval
  name: '@deepseek-ai/dsh-user-approval'
  config:
    policy: never

- id: agent-spine
  name: '@deepseek-ai/dsh-agent-spine-demo'
  config:
    includeHarnessIdentity: false
    includeRuntimeContext: false
    persona: !!js process.env.DSH_SYSTEM_PROMPT ?? 'You are a coding assistant operating through Feishu.'
    tools:
      mode: native
    workspaceContext: false
    skills:
      enabled: false
    toolBash:
      enableRunInBackground: false
    toolJobs: false
    goals: false
    maxParallelToolCalls: 1

- id: sessions
  name: '@deepseek-ai/dsh-session-persistence-jsonl'
  config:
    root: !!js process.env.DSH_SESSION_ROOT ?? './.dsh-sessions'
    compression: zstd

- id: session-checkpoints
  name: '@deepseek-ai/dsh-session-checkpoint-policy'

- id: tool-todo
  name: '@deepseek-ai/dsh-tool-todo'
  config:
    allowParallelInProgress: false

- id: fs-sandbox
  name: '@deepseek-ai/dsh-fs-sandbox'
  config:
    cwd: !!js process.env.DSH_CWD ?? process.cwd()

- id: fs-observation-policy
  name: '@deepseek-ai/dsh-fs-observation-policy'

- id: tool-fs
  name: '@deepseek-ai/dsh-tool-fs'

- id: token-meter
  name: '@deepseek-ai/dsh-token-meter'

- id: compaction-basic
  name: '@deepseek-ai/dsh-compaction-basic'
  config:
    thresholdRatio: 0.8
    retainRatio: 0.16
    maxTokens: 8192
    compactionRetries: 1
`;

export function dshProfileText(): string {
  return PROFILE;
}

export async function ensureDshProfile(file: string = paths.dshProfileFile): Promise<string> {
  try {
    if ((await readFile(file, 'utf8')) === PROFILE) return file;
  } catch {
    /* missing or unreadable: replace below */
  }

  await mkdir(dirname(file), { recursive: true });
  const temp = `${file}.tmp-${process.pid}-${randomUUID()}`;
  try {
    await writeFile(temp, PROFILE, { encoding: 'utf8', mode: 0o644 });
    await rename(temp, file);
  } finally {
    await rm(temp, { force: true }).catch(() => undefined);
  }
  return file;
}
